import { visit } from 'unist-util-visit';
import fs from 'node:fs';
import path from 'node:path';

const ENV_TOKEN = /\{environment:(\w+)\}/g;

/** @type {Record<string, string> | null} */
let _vars = null;

function resolvePlatformAndLang() {
    const platform = process.env.PLATFORM;
    const lang     = process.env.LANG_CODE;
    if (platform && lang) return { platform, lang };

    try {
        const cfgPath = path.resolve(process.cwd(), '.platform.json');
        if (fs.existsSync(cfgPath)) {
            const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8'));
            return {
                platform: platform || cfg.platform || 'React',
                lang:     lang     || cfg.lang     || 'en',
            };
        }
    } catch { /* ignore */ }

    return { platform: platform || 'React', lang: lang || 'en' };
}

function getVars() {
    if (_vars) return _vars;

    const nodeEnv            = process.env.NODE_ENV || 'development';
    const { platform, lang } = resolvePlatformAndLang();

    try {
        const envJsonPath = path.resolve(process.cwd(), 'generated', platform, lang, 'environment.json');
        const envAll      = JSON.parse(fs.readFileSync(envJsonPath, 'utf-8'));
        _vars = envAll[nodeEnv] ?? envAll['development'] ?? {};
    } catch {
        _vars = {};
    }

    return _vars;
}

/**
 * Remark plugin that resolves `{environment:key}` tokens in markdown content
 * at build time. Reads dist/{Platform}/{lang}/environment.json (generated by
 * scripts/generate.mjs) and selects the block matching NODE_ENV.
 */
export function remarkEnv() {
    return (tree) => {
        const vars = getVars();
        visit(tree, (node) => {
            if (node.type === 'html' && node.value) {
                node.value = node.value.replace(ENV_TOKEN, (_, key) => vars[key] ?? `{environment:${key}}`);
            }
            if (node.type === 'text' && node.value) {
                node.value = node.value.replace(ENV_TOKEN, (_, key) => vars[key] ?? `{environment:${key}}`);
            }
            if (node.type === 'link' && node.url) {
                node.url = node.url.replace(ENV_TOKEN, (_, key) => vars[key] ?? `{environment:${key}}`);
            }
            if (node.type === 'image' && node.url) {
                node.url = node.url.replace(ENV_TOKEN, (_, key) => vars[key] ?? `{environment:${key}}`);
            }
            if (node.type === 'definition' && node.url) {
                node.url = node.url.replace(ENV_TOKEN, (_, key) => vars[key] ?? `{environment:${key}}`);
            }
        });
    };
}
