# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build React CI

on:
  push:
    branches: [ master, vnext ]
  pull_request:
    branches: [ master, vnext ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: npm ci
    - name: DotNet tool restore
      run: dotnet tool restore
    - name: Build React
      run: npm run build-docfx-react
    - name: Test React
      run: npm run test --testPlatform=React
