parameters:
  - name: buildType
  - name: platform
  - name: language
  - name: isVerbose
    default: false

steps:
  - task: Npm@1
    displayName: 'Build ${{ parameters.platform }} ${{ parameters.buildType }} ${{ parameters.language }}'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)'
      verbose: ${{ parameters.isVerbose }}
      customCommand: 'run build${{ parameters.buildType }} -- --plat=${{ parameters.platform }} --lang=${{ parameters.language }}'

  - task: ArchiveFiles@2
    displayName: 'Package ${{ parameters.platform }} ${{ parameters.language }} - zip'
    inputs:
      verbose: ${{ parameters.isVerbose }}
      rootFolderOrFile: $(Build.SourcesDirectory)/dist/${{ parameters.platform }}/${{ parameters.language }}/_site
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.platform }}_${{ parameters.language }}_${{ parameters.buildType }}.zip
      replaceExistingArchive: true

  - task: GitVersion@5
    displayName: 'Clone and checkout the Branch to push changes in'
    inputs:
      updateAssemblyInfo: true
  - script: |
      git clone https://$(githubUser):$(githubToken)@github.com/ESShared/ignite-ui-docfx.git
      git remote add upstream https://github.com/IgniteUI/igniteui-docfx.git
      git fetch upstream
      git checkout --track origin/$(Build.SourceBranchName)
      git merge upstream/$(Build.SourceBranchName)
      git push origin
      git checkout -b $(branchName)_$(Build.SourceBranchName)
      git pull origin $(branchName)_$(Build.SourceBranchName)
      git merge $(Build.SourceBranchName)


  - task: CopyFiles@2
    displayName: 'Copy the build files to the Git repo'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\dist\Angular\$(languageToBuild)'
      TargetFolder: '$(Build.SourcesDirectory)\ignite-ui-docfx\$(languageToBuild)'

  - task: GitVersion@5
    displayName: 'Commit the changes and make a PR'
    inputs:
      updateAssemblyInfo: true
  - script: |
      git add -A
      git commit -m "Adding changes from build $(Build.BuildNumber)"
      git push --set-upstream origin $(branchName)_$(Build.SourceBranchName)
  
  - task: CreatePullRequest@1
    inputs:
      repoType: 'GitHub'
      githubEndpoint: 'ESShared'
      githubRepository: 'IgniteUI/igniteui-docfx'
      sourceBranch: '$(branchName)'
      targetBranch: 'vNext'
      title: 'Changes from $(Build.DefinitionName)'
