parameters:
  - name: buildType
  - name: platform
  - name: language
  - name: isVerbose
    default: false

steps:
  - task: Npm@1
    displayName: 'Build ${{ parameters.platform }} ${{ parameters.buildType }} ${{ parameters.language }}'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)'
      verbose: ${{ parameters.isVerbose }}
      customCommand: 'run build${{ parameters.platform }} -- --plat=${{ parameters.platform }} --lang=${{ parameters.language }}'

#  - task: ArchiveFiles@2
#    displayName: 'Package ${{ parameters.platform }} ${{ parameters.language }} - zip'
#    inputs:
#      verbose: ${{ parameters.isVerbose }}
#      rootFolderOrFile: $(Build.SourcesDirectory)/dist/${{ parameters.platform }}/${{ parameters.language }}/_site
#      includeRootFolder: false
#      archiveType: 'zip'
#      archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.platform }}_${{ parameters.language }}_${{ parameters.buildType }}.zip
#      replaceExistingArchive: true

  - script: |
      git clone https://$(githubUser):$(githubToken)@github.com/IgniteUI/ignite-ui-docfx.git
      git checkout -b ESShared/XPlaform_EN_$(Build.BuildNumber) origin/vnext
    displayName: 'Clone and checkout the Branch to push changes in'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - task: CopyFiles@2
    displayName: 'Copy the build files to the Git repo'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\dist\Angular\$(languageToBuild)'
      TargetFolder: '$(Build.SourcesDirectory)\ignite-ui-docfx\$(languageToBuild)'

  - script: |
      git add -A
      git commit -m "Adding changes from build $(Build.BuildNumber)"
      git push
    displayName: 'Commit the changes and make a PR'
    workingDirectory: $(System.DefaultWorkingDirectory)
  
  - task: CreatePullRequest@1
    inputs:
      repoType: 'GitHub'
      githubEndpoint: 'ESShared'
      githubRepository: 'IgniteUI/igniteui-docfx'
      sourceBranch: 'ESShared/XPlaform_EN_$(Build.BuildNumber)'
      targetBranch: 'vNext'
      title: 'Changes from $(Build.DefinitionName)'
