parameters:
  - name: buildType
  - name: platform
  - name: language
  - name: isVerbose
    default: false

steps:
  - task: Npm@1
    displayName: 'Build ${{ parameters.platform }} ${{ parameters.buildType }} ${{ parameters.language }}'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)'
      verbose: ${{ parameters.isVerbose }}
      customCommand: 'run build${{ parameters.platform }} -- --plat=${{ parameters.platform }} --lang=${{ parameters.language }}'

  - script: |
      git clone https://$(githubUser):$(githubToken)@github.com/IgniteUI/igniteui-docfx.git
    displayName: 'Clone igniteui-docfx'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      git fetch origin
      git checkout -b ESShared/XPlaform_${{ parameters.language }}_$(Build.BuildNumber) origin/$(Build.SourceBranchName)
    displayName: 'Checkout a new branch to push changes in'
    workingDirectory: $(Build.SourcesDirectory)\igniteui-docfx

  - task: CopyFiles@2
    displayName: 'Copy the build files to the Git repo'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\dist\Angular\${{ parameters.language }}'
      TargetFolder: '$(Build.SourcesDirectory)\igniteui-docfx\${{ parameters.language }}'
      OverWrite: true

  - script: |
      git add -A
      git commit -m "Adding changes from build $(Build.BuildNumber)"
      git push -u origin ESShared/XPlaform_${{ parameters.language }}_$(Build.BuildNumber)
    displayName: 'Commit the changes and make a PR'
    workingDirectory: $(System.DefaultWorkingDirectory)\igniteui-docfx
  
  - task: CreatePullRequest@1
    inputs:
      repoType: 'GitHub'
      githubEndpoint: 'ESShared'
      githubRepository: 'IgniteUI/igniteui-docfx'
      sourceBranch: 'ESShared/XPlaform_${{ parameters.language }}_$(Build.BuildNumber)'
      targetBranch: '$(Build.SourceBranchName)'
      title: 'Changes from $(Build.DefinitionName)'
