parameters:
  - name: jobTemplate
  - name: buildType
  - name: component
  - name: platform
  - name: language
  - name: isVerbose
    default: false

jobs:
- job: ${{ parameters.jobName }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '16.x'
  - script: echo '$(Build.BuildNumber)'
    displayName: 'Display Build Number'

  - script: echo '${{ parameters.buildType }}'
    displayName: 'Display Build Type'

  - task: RegexReplace@3
    displayName: 'replace environment in doc/docfx'
    inputs:
      InputSearchPattern: |
        doc\**\*.*
        docfx\**\*.*
      FindRegex: 'environment:dvDemosBaseUrl'
      ReplaceRegex: 'environment:demosBaseUrl'
      UseUTF8: true
      UseRAW: true
    enabled: false

  - task: Npm@1
    displayName: 'npm cache clean'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)'
      verbose: ${{ parameters.isVerbose }}
      customCommand: 'cache clean --force'
    continueOnError: true

  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)'
      verbose: ${{ parameters.isVerbose }}
      customCommand: ci

  - task: Npm@1
    displayName: 'Build ${{ parameters.platform }} ${{ parameters.buildType }} ${{ parameters.language }}'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)'
      verbose: ${{ parameters.isVerbose }}
      customCommand: 'run build-${{ parameters.buildType }} -- --plat=${{ parameters.platform }} --lang=${{ parameters.language }}'

  - task: ArchiveFiles@2
    displayName: 'Package ${{ parameters.platform }} ${{ parameters.language }} - zip'
    inputs:
      verbose: ${{ parameters.isVerbose }}
      rootFolderOrFile: $(Build.SourcesDirectory)/dist/${{ parameters.platform }}/${{ parameters.language }}/_site
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: $(Build.ArtifactStagingDirectory)/$(component)_${{ parameters.platform }}_${{ parameters.language }}_${{ parameters.buildType }}.zip
      replaceExistingArchive: true