trigger:
  branches:
    include:
    - vnext
    - master
pr:
  branches:
    exclude:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  component: 'XPlatDocFX'
  buildType: 'staging'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildType: 'production'

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildDocs
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
    - script: echo '$(Build.BuildNumber)'
      displayName: 'Display Build Number'

    - script: echo '$(buildType)'
      displayName: 'Display Build Type'

    - task: RegexReplace@3
      displayName: 'replace environment in doc/docfx'
      inputs:
        InputSearchPattern: |
          doc\**\*.*
          docfx\**\*.*
        FindRegex: 'environment:dvDemosBaseUrl'
        ReplaceRegex: 'environment:demosBaseUrl'
        UseUTF8: true
        UseRAW: true
      enabled: false

    - task: Npm@1
      displayName: 'npm cache clean'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: false
        customCommand: 'cache clean --force'
      continueOnError: true

    - task: Npm@1
      displayName: 'npm ci'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: false
        customCommand: ci

    - task: Npm@1
      displayName: 'Build WebComponents'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: true
        customCommand: 'run buildWebComponents'

    - task: Npm@1
      displayName: 'Build WebComponents $(buildType) en'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: true
        customCommand: 'run build-$(buildType) -- --plat=WebComponents --lang=en'

    - task: ArchiveFiles@2
      displayName: 'Package WebComponents en - zip'
      inputs:
        verbose: true
        # dist\$plat$\$langFolder$\_site
        rootFolderOrFile: $(Build.SourcesDirectory)/dist/WebComponents/en/_site
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: $(Build.ArtifactStagingDirectory)/$(component)_WebComponents_en_$(buildType).zip
        replaceExistingArchive: true

    - task: Npm@1
      displayName: 'Build WebComponents $(buildType) jp'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: true
        customCommand: 'run build-$(buildType) -- --plat=WebComponents --lang=jp'

    - task: ArchiveFiles@2
      displayName: 'Package WebComponents jp - zip'
      inputs:
        verbose: true
        # dist\$plat$\$langFolder$\_site
        rootFolderOrFile: $(Build.SourcesDirectory)/dist/WebComponents/jp/_site
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: $(Build.ArtifactStagingDirectory)/$(component)_WebComponents_jp_$(buildType).zip
        replaceExistingArchive: true

    - task: Npm@1
      displayName: 'Build Blazor EN'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: true
        customCommand: 'run build-$(buildType) -- --plat=Blazor --lang=en'

#    - task: NuGetCommand@2
#      displayName: 'Package Blazor EN'
#      inputs:
#        command: pack
#        packagesToPack: '$(Build.SourcesDirectory)\$(component).nuspec'
#        versioningScheme: byBuildNumber
#        buildProperties: 'langFolder=en;type=$(buildType);plat=Blazor'

    - task: ArchiveFiles@2
      displayName: 'Package Blazor en - zip'
      inputs:
        verbose: true
        # dist\$plat$\$langFolder$\_site
        rootFolderOrFile: $(Build.SourcesDirectory)/dist/Blazor/en/_site
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: $(Build.ArtifactStagingDirectory)/$(component)_Blazor_en_$(buildType).zip
        replaceExistingArchive: true

    - task: Npm@1
      displayName: 'Build Blazor JP'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: true
        customCommand: 'run build-$(buildType) -- --plat=Blazor --lang=jp'

    - task: ArchiveFiles@2
      displayName: 'Package Blazor jp - zip'
      inputs:
        verbose: true
        # dist\$plat$\$langFolder$\_site
        rootFolderOrFile: $(Build.SourcesDirectory)/dist/Blazor/jp/_site
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: $(Build.ArtifactStagingDirectory)/$(component)_Blazor_jp_$(buildType).zip
        replaceExistingArchive: true

    - task: Npm@1
      displayName: 'Build React EN'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: true
        customCommand: 'run build-$(buildType) -- --plat=React --lang=en'

#    - task: NuGetCommand@2
#      displayName: 'Package React EN'
#      inputs:
#        command: pack
#        packagesToPack: '$(Build.SourcesDirectory)\$(component).nuspec'
#        versioningScheme: byBuildNumber
#        buildProperties: 'langFolder=en;type=$(buildType);plat=React'

    - task: ArchiveFiles@2
      displayName: 'Package React en - zip'
      inputs:
        verbose: true
        # dist\$plat$\$langFolder$\_site
        rootFolderOrFile: $(Build.SourcesDirectory)/dist/React/en/_site
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: $(Build.ArtifactStagingDirectory)/$(component)_React_en_$(buildType).zip
        replaceExistingArchive: true

    - task: Npm@1
      displayName: 'Build React JP'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: true
        customCommand: 'run build-$(buildType) -- --plat=React --lang=jp'

    - task: ArchiveFiles@2
      displayName: 'Package React jp - zip'
      inputs:
        verbose: true
        # dist\$plat$\$langFolder$\_site
        rootFolderOrFile: $(Build.SourcesDirectory)/dist/React/jp/_site
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: $(Build.ArtifactStagingDirectory)/$(component)_React_jp_$(buildType).zip
        replaceExistingArchive: true

#    - task: PublishBuildArtifacts@1
#      displayName: 'Publish Artifacts'
#      inputs:
#        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#        ArtifactName: 'drop'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish pipeline artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: '$(component)'
