trigger:
  branches:
    include:
    - vnext
    - master
    - 'sstoychev/ng-pipes'
  paths:
    exclude:
    - '**/jp/*'
    - '**/kr/*'
pr:
  branches:
    exclude:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildType: 'production'
  ${{ else }}:  
    buildType: 'staging'

resources:
  repositories:
    - repository: IgniteUIDocFX # In a different organization
      endpoint: ESShared
      type: github
      name: IgniteUI/igniteui-docfx

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildDocs
    steps:
      - checkout: self
      - checkout: IgniteUIDocFX
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '16.x'

      - task: RegexReplace@3
        displayName: 'replace environment in doc/docfx'
        inputs:
          InputSearchPattern: |
            doc\**\*.*
            docfx\**\*.*
          FindRegex: 'environment:dvDemosBaseUrl'
          ReplaceRegex: 'environment:demosBaseUrl'
          UseUTF8: true
          UseRAW: true
        enabled: false

      - task: Npm@1
        displayName: 'npm ci'
        inputs:
          command: custom
          workingDir: '$(Build.SourcesDirectory)'
          #verbose: ${{ parameters.isVerbose }}
          customCommand: ci

      - template: templates/build-steps-template.yml
        parameters:
          buildType: $(buildType)
          platform: WebComponents
          language: en
          verbose: ${{ parameters.isVerbose }}

      - template: templates/build-steps-template.yml
        parameters:
          buildType: $(buildType)
          platform: Blazor
          language: en
          verbose: ${{ parameters.isVerbose }}

      - template: templates/build-steps-template.yml
        parameters:
          buildType: $(buildType)
          platform: React
          language: en
          verbose: ${{ parameters.isVerbose }}


      - task: PublishPipelineArtifact@1
        displayName: 'Publish pipeline artifacts'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'XPlatDocFX'
