trigger:
  branches:
    include:
    - vnext
    - master
  paths:
    exclude:
    - '**/jp/*'
    - '**/kr/*'
pr:
  branches:
    exclude:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  buildType: 'staging'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildType: 'production'

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildDocs
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '16.x'

      - task: RegexReplace@3
        displayName: 'replace environment in doc/docfx'
        inputs:
          InputSearchPattern: |
            doc\**\*.*
            docfx\**\*.*
          FindRegex: 'environment:dvDemosBaseUrl'
          ReplaceRegex: 'environment:demosBaseUrl'
          UseUTF8: true
          UseRAW: true
        enabled: false

      - task: Npm@1
        displayName: 'npm ci'
        inputs:
          command: custom
          workingDir: '$(Build.SourcesDirectory)'
          verbose: ${{ parameters.isVerbose }}
          customCommand: ci

#      - template: templates/build-steps-template.yml
#        parameters:
#          buildType: $(buildType)
#          platform: WebComponents
#          language: en
#
#      - template: templates/build-steps-template.yml
#        parameters:
#          buildType: $(buildType)
#          platform: Blazor
#          language: en
#
#      - template: templates/build-steps-template.yml
#        parameters:
#          buildType: $(buildType)
#          platform: React
#          language: en

      - template: templates/build-steps-make-pr.tml
        parameters:
          buildType: $(buildType)
          platform: Angular
          language: en

      - task: PublishPipelineArtifact@1
        displayName: 'Publish pipeline artifacts'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'XPlatDocFX'

