trigger:
  branches:
    include:
    - vnext
    - master
  paths:
    exclude:
    - jp/*
    - kr/*
pr:
  branches:
    exclude:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  component: 'XPlatDocFX'
  buildType: 'staging'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildType: 'production'

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - template: templates/job-template.yml
    parameters:
      jobName: WebComponents_EN
      buildType: $(buildType)
      platform: WebComponents
      language: en

  - template: templates/job-template.yml
    parameters:
      jobName: React_EN
      buildType: $(buildType)
      platform: React
      language: en

  - template: templates/job-template.yml
    parameters:
      jobName: Blazor_EN
      buildType: $(buildType)
      platform: Blazor
      language: en