trigger:
  branches:
    include:
    - vnext
    - master
  paths:
    exclude:
    - jp/*
    - kr/*
pr:
  branches:
    exclude:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

schedules:
- cron: "*/30 * * * *"
  displayName: 'Stability verification schedule'
  always: true
  branches:
    include:
    - azure-pipelines

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  buildType: 'staging'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildType: 'production'

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildDocs
    steps:
    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: WebComponents
        language: en

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: Blazor
        language: en

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: React
        language: en

    - task: PublishPipelineArtifact@1
      displayName: 'Publish pipeline artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'XPlatDocFX'