trigger:
  branches:
    include:
    - vnext
    - master
  paths:
    exclude:
    - '**/en/*'

# This pipeline is meant to build specific branches for deployment. It's not meant to be a part of PR validation.
pr: none

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false
- name: shouldCleanPostExectuion
  displayName: 'Clean all pipeline dirs after the pipeline finishes?'
  type: boolean
  default: true

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  - name: buildType
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: 'production'
    ${{ else }}:  
      value: 'staging'
  # This is the variable that the gulp script looks at internally. This is the only way I know how to pass it for Angular
  - name: 'NODE_ENV'
    value: '$(buildType)'

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildDocs
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'

    - task: RegexReplace@3
      displayName: 'replace environment in doc/docfx'
      inputs:
        InputSearchPattern: |
          doc\**\*.*
          docfx\**\*.*
        FindRegex: 'environment:dvDemosBaseUrl'
        ReplaceRegex: 'environment:demosBaseUrl'
        UseUTF8: true
        UseRAW: true
      enabled: false

    - task: Npm@1
      displayName: 'npm ci'
      inputs:
        command: custom
        workingDir: '$(Build.SourcesDirectory)'
        verbose: ${{ parameters.isVerbose }}
        customCommand: 'ci --production=false'

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: WebComponents
        language: jp
        workingDir: '$(Build.SourcesDirectory)'
        isVerbose: ${{ parameters.isVerbose }}

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: Blazor
        language: jp
        workingDir: '$(Build.SourcesDirectory)'
        isVerbose: ${{ parameters.isVerbose }}

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: React
        language: jp
        workingDir: '$(Build.SourcesDirectory)'
        isVerbose: ${{ parameters.isVerbose }}

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: Angular
        language: jp
        isVerbose: ${{ parameters.isVerbose }}
        workingDir: '$(Build.SourcesDirectory)'

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: WebComponents
        language: kr
        workingDir: '$(Build.SourcesDirectory)'
        isVerbose: ${{ parameters.isVerbose }}

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: Blazor
        language: kr
        workingDir: '$(Build.SourcesDirectory)'
        isVerbose: ${{ parameters.isVerbose }}

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: React
        language: kr
        workingDir: '$(Build.SourcesDirectory)'
        isVerbose: ${{ parameters.isVerbose }}

    - template: templates/build-steps-template.yml
      parameters:
        buildType: $(buildType)
        platform: Angular
        language: kr
        isVerbose: ${{ parameters.isVerbose }}
        workingDir: '$(Build.SourcesDirectory)'

    # Angular doesn't produce an artifact that we can publish right now.
    - task: PublishPipelineArtifact@1
      displayName: 'Publish pipeline artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'XPlatDocFX'

    - ${{ if eq(parameters.shouldCleanPostExectuion, true) }}:
      - task: PostBuildCleanup@4
