trigger:
  branches:
    include:
    - vnext
    - master

pr:
  branches:
    exclude:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

stages:
- stage: Build
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: echo "Hello world"
          #- task: KubernetesManifest@0

